/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciaviajes.presentacion;


import agenciaviajes.negocio.GestorClientes;
import java.awt.Color;
import java.awt.Graphics;
import java.text.DecimalFormat;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author Libardo Pantoja, Ricardo Zambrano Cuarto observador
 */
public class GUIEstadisticaPorSexoGrafica extends javax.swing.JFrame implements AView {

    private float porcentajeHombres;
    private float  porcentajeMujeres;
    private static final int ancho = 100;
    private static final int alto = 260;
    private int altoHombres;
    private int altoMujeres;
    /**
     * Constructor
     *
     * @param h horizontal position
     * @param v vertical position
     */
    public GUIEstadisticaPorSexoGrafica(int h, int v) {
        porcentajeHombres = 0;
        porcentajeMujeres = 0;
        altoHombres = 0;
        altoMujeres = 0;
        initComponents();
        this.setSize(320, 300);
        this.setLocation(h, v);
        this.setVisible(true);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estadísticas");

        myPanel.setBackground(java.awt.Color.white);
        getContentPane().add(myPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables



    @Override
    public void actualizar(AModel amodel) {
        GestorClientes gestor = (GestorClientes) amodel;
        int totalHombres = gestor.getTotalHombres();
        int totalMujeres = gestor.getTotalMujeres();
        graficar(totalHombres, totalMujeres);
    }
    
     private void graficar(int totalHombres, int totalMujeres)
    {
        //Total de personas, hombre y mujeres.
        int totalPersonas = totalHombres + totalMujeres;
        
        //Obtenemos los porcentajes con rexpecto a los hombres y las mujeres
        this.porcentajeHombres = (100 * ((float)(totalHombres))) / ((float)(totalPersonas));
        this.porcentajeMujeres = (100 * ((float)(totalMujeres))) / ((float)(totalPersonas));
        
        //En estas variables calculamos el porcentaje que hay que pintar en los rectangulos
        this.altoHombres = (((int)(porcentajeHombres)) * alto) / 100; 
        this.altoMujeres = (((int)(porcentajeMujeres)) * alto) / 100; 
        
        Graphics g = myPanel.getGraphics();
        //Implementamos un metodo que dibuje las graficas de porcentajes
        paintComponent(g);
     
    }
    
    //Metodo de dibujo
    @SuppressWarnings("empty-statement")
    public void paintComponent(Graphics g )
    {
        super.paintComponents(g);;
        
        g.setColor(Color.black);
        g.drawRect(60, 60, ancho, alto);
        g.drawRect(260, 60, ancho, alto);
        
        g.drawString("Hombres", 65, 345);
        g.drawString("Mujeres", 265, 345);
        g.drawString("" + porcentajeHombres +" %", 90, 55);
        g.drawString("" + porcentajeMujeres + " %", 290, 55);
       
        g.setColor(Color.RED);
        g.fillRect(61, 60 + (alto - altoHombres), ancho-1, altoHombres);
        g.fillRect(261, 60 + (alto- altoMujeres), ancho-1, altoMujeres);
    }

}
